### ISSUE TITLE
Need more instruction in using neticspy 

### ISSUE THREAD

**Issue by MartinChiaHsinLiu** [bhi-kimlab/neticspy#1]
Hi, 

I am a neticspy end-user.
I successfully install neticspy in my computer(debian 9) with Python 2.7.13. 

When I try to conduct the example command with the file "adj_lar_com.mat" downloaded from [https://github.com/cbg-ethz/netics/blob/master/data/adj_lar_com.mat]
It failed and I guess that it may be the format problem.
As a consequence, I use the following command in the python prompt to transform the mat to a csv format:

import pandas as pd
import numpy
from scipy.io import loadmat
data_dict = loadmat('adj_lar_com.mat')
data_array = data_dict['adj_lar_com']
data_array = data_array.transpose(1, 0)
dataframe = pd.DataFrame(data_array) 
dataframe.to_csv(r"adj_lar_com.csv")

Then I try to conduct neticspy  again.
The command I run:
neticspy diffuse --adj adj_lar_com.csv --beta 0.4 --output testout 
It turn back the following message as I use the .mat file.

Traceback (most recent call last):
  File "/usr/local/bin/neticspy", line 7, in <module>
    from neticspy.cli import main
  File "/usr/local/lib/python2.7/dist-packages/neticspy/__init__.py", line 120
    logger.info(f'Successfully saved diffusion matrix to {output}.')
                                                                  ^
SyntaxError: invalid syntax

**Comment by BonilKoo** [comment]
Hi,

I'm sorry for the inconvenience caused by not specifying details.

Neticspy is not available with Python 2. Use Python 3.

In addition, neticspy requires an adjacency matrix file separated by tab, not comma.

I hope our implementation of NetICS help you.

Thanks.

**Comment by MartinChiaHsinLiu** [comment]
Thanks a million for your replying so quickly.
I change my version to python3.5.3 and try to import the neticspy install in my local home.
I get a different error message as following when I try to import the package:

Python 3.5.3 (default, Apr  5 2021, 09:00:41)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
'>>> import neticspy'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/martinliu/.local/lib/python3.5/site-packages/neticspy/__init__.py", line 120
    logger.info(f'Successfully saved diffusion matrix to {output}.')
                                                                  ^
SyntaxError: invalid syntax
'>>>'

**Comment by BonilKoo** [comment]
I'm not sure what is causing the problem.

How about try to remove and reinstall neticspy with pip?

If that doesn't work again, comment out line 120 in "/home/martinliu/.local/lib/python3.5/site-packages/neticspy/init.py".
